name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"

  - title: "🐛 Bug Fixes"
    labels:
      - "bug"

  - title: "🧰 Refactoring & Performance"
    labels:
      - "refactor"
      - "performance"

  - title: "🔒 Security"
    labels:
      - "security"

  - title: "📚 Documentation"
    labels:
      - "documentation"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

template: |
  ## What’s Changed

  $CHANGES

  ## Installation

  See the project documentation for installation and upgrade instructions.
