# stack.yaml for Surypus
resolver: nightly-2026-04-05

packages:
  - surypus-common
  - surypus-api-shim
  - surypus-api-core
  - .

ghc-options:
  "$locals": -Wall -Wcompat

allow-newer: true
allow-different-user: true
system-ghc: false

extra-deps:
  - validation-selective-0.2.0.0
  - cryptonite-0.30
  - servant-swagger-1.2.1
  - swagger2-2.8.10
