// Generated by surypus-codegen — DO NOT EDIT MANUALLY
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Dialog {
    id: root
    title: "Create CustomerEntity"
    modal: true
    standardButtons: Dialog.Ok | Dialog.Cancel
    signal created(var payload)
    property var initial: null

    onAboutToShow: {
        if (root.initial) {
            // prefill controls from initial
            if (typeof fld_code !== 'undefined') fld_code.text = root.initial["code"] !== undefined && root.initial["code"] !== null ? String(root.initial["code"]) : ""
            if (typeof fld_name !== 'undefined') fld_name.text = root.initial["name"] !== undefined && root.initial["name"] !== null ? String(root.initial["name"]) : ""
            if (typeof fld_email !== 'undefined') fld_email.text = root.initial["email"] !== undefined && root.initial["email"] !== null ? String(root.initial["email"]) : ""
            if (typeof fld_creditLimit !== 'undefined') fld_creditLimit.text = root.initial["creditLimit"] !== undefined && root.initial["creditLimit"] !== null ? String(root.initial["creditLimit"]) : ""
            if (typeof fld_active !== 'undefined') fld_active.text = root.initial["active"] !== undefined && root.initial["active"] !== null ? String(root.initial["active"]) : ""
            if (typeof fld_createdAt !== 'undefined') fld_createdAt.text = root.initial["createdAt"] !== undefined && root.initial["createdAt"] !== null ? String(root.initial["createdAt"]) : ""

        } else {
            if (typeof fld_code !== 'undefined') fld_code.text = ""
            if (typeof fld_name !== 'undefined') fld_name.text = ""
            if (typeof fld_email !== 'undefined') fld_email.text = ""
            if (typeof fld_creditLimit !== 'undefined') fld_creditLimit.text = ""
            if (typeof fld_active !== 'undefined') fld_active.text = ""
            if (typeof fld_createdAt !== 'undefined') fld_createdAt.text = ""

        }
    }

    contentItem: ScrollView {
        width: 420; height: Math.min(implicitHeight, 480)
        ColumnLayout {
            width: parent.width
            spacing: 8
            TextField { placeholderText: "code"; id: fld_code; width: parent.width }
            Label { text: "code"; font.pointSize: 10 }
            TextField { placeholderText: "name"; id: fld_name; width: parent.width }
            Label { text: "name"; font.pointSize: 10 }
            TextField { placeholderText: "email"; id: fld_email; width: parent.width }
            Label { text: "email"; font.pointSize: 10 }
            TextField { placeholderText: "creditLimit"; id: fld_creditLimit; width: parent.width }
            Label { text: "creditLimit"; font.pointSize: 10 }
            TextField { placeholderText: "active"; id: fld_active; width: parent.width }
            Label { text: "active"; font.pointSize: 10 }
            TextField { placeholderText: "createdAt"; id: fld_createdAt; width: parent.width }
            Label { text: "createdAt"; font.pointSize: 10 }
        }
    }

    onAccepted: {
        var payload = {};
        (payload["code"] = fld_code.text)
        (payload["name"] = fld_name.text)
        (payload["email"] = fld_email.text)
        (payload["creditLimit"] = fld_creditLimit.text)
        (payload["active"] = fld_active.text)
        (payload["createdAt"] = fld_createdAt.text)
        if (root.initial && root.initial.id !== undefined) payload.id = root.initial.id;
        root.created(payload);
    }
}

// Generated by surypus-codegen
