// Generated by surypus-codegen — DO NOT EDIT MANUALLY
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Dialog {
    id: root
    title: "Create PersonEntity"
    modal: true
    standardButtons: Dialog.Ok | Dialog.Cancel
    signal created(var payload)
    property var initial: null

    onAboutToShow: {
        if (root.initial) {
            // prefill controls from initial
            if (typeof fld_code !== 'undefined') fld_code.text = root.initial["code"] !== undefined && root.initial["code"] !== null ? String(root.initial["code"]) : ""
            if (typeof fld_name !== 'undefined') fld_name.text = root.initial["name"] !== undefined && root.initial["name"] !== null ? String(root.initial["name"]) : ""
            if (typeof fld_inn !== 'undefined') fld_inn.text = root.initial["inn"] !== undefined && root.initial["inn"] !== null ? String(root.initial["inn"]) : ""
            if (typeof fld_kpp !== 'undefined') fld_kpp.text = root.initial["kpp"] !== undefined && root.initial["kpp"] !== null ? String(root.initial["kpp"]) : ""
            if (typeof fld_personType !== 'undefined') fld_personType.text = root.initial["personType"] !== undefined && root.initial["personType"] !== null ? String(root.initial["personType"]) : ""
            if (typeof fld_status !== 'undefined') fld_status.text = root.initial["status"] !== undefined && root.initial["status"] !== null ? String(root.initial["status"]) : ""

        } else {
            if (typeof fld_code !== 'undefined') fld_code.text = ""
            if (typeof fld_name !== 'undefined') fld_name.text = ""
            if (typeof fld_inn !== 'undefined') fld_inn.text = ""
            if (typeof fld_kpp !== 'undefined') fld_kpp.text = ""
            if (typeof fld_personType !== 'undefined') fld_personType.text = ""
            if (typeof fld_status !== 'undefined') fld_status.text = ""

        }
    }

    contentItem: ScrollView {
        width: 420; height: Math.min(implicitHeight, 480)
        ColumnLayout {
            width: parent.width
            spacing: 8
            TextField { placeholderText: "code"; id: fld_code; width: parent.width }
            Label { text: "code"; font.pointSize: 10 }
            TextField { placeholderText: "name"; id: fld_name; width: parent.width }
            Label { text: "name"; font.pointSize: 10 }
            TextField { placeholderText: "inn"; id: fld_inn; width: parent.width }
            Label { text: "inn"; font.pointSize: 10 }
            TextField { placeholderText: "kpp"; id: fld_kpp; width: parent.width }
            Label { text: "kpp"; font.pointSize: 10 }
            TextField { placeholderText: "personType"; id: fld_personType; width: parent.width }
            Label { text: "personType"; font.pointSize: 10 }
            TextField { placeholderText: "status"; id: fld_status; width: parent.width }
            Label { text: "status"; font.pointSize: 10 }
        }
    }

    onAccepted: {
        var payload = {};
        (payload["code"] = fld_code.text)
        (payload["name"] = fld_name.text)
        (payload["inn"] = fld_inn.text)
        (payload["kpp"] = fld_kpp.text)
        (payload["personType"] = fld_personType.text)
        (payload["status"] = fld_status.text)
        if (root.initial && root.initial.id !== undefined) payload.id = root.initial.id;
        root.created(payload);
    }
}

// Generated by surypus-codegen
