// Generated by surypus-codegen — DO NOT EDIT MANUALLY
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Dialog {
    id: root
    title: "Create ProductionOrderEntity"
    modal: true
    standardButtons: Dialog.Ok | Dialog.Cancel
    signal created(var payload)
    property var initial: null

    onAboutToShow: {
        if (root.initial) {
            // prefill controls from initial
            if (typeof fld_number !== 'undefined') fld_number.text = root.initial["number"] !== undefined && root.initial["number"] !== null ? String(root.initial["number"]) : ""
            if (typeof fld_productId !== 'undefined') fld_productId.text = root.initial["productId"] !== undefined && root.initial["productId"] !== null ? String(root.initial["productId"]) : ""
            if (typeof fld_qty !== 'undefined') fld_qty.text = root.initial["qty"] !== undefined && root.initial["qty"] !== null ? String(root.initial["qty"]) : ""
            if (typeof fld_dueDate !== 'undefined') fld_dueDate.text = root.initial["dueDate"] !== undefined && root.initial["dueDate"] !== null ? String(root.initial["dueDate"]) : ""
            if (typeof fld_status !== 'undefined') fld_status.text = root.initial["status"] !== undefined && root.initial["status"] !== null ? String(root.initial["status"]) : ""

        } else {
            if (typeof fld_number !== 'undefined') fld_number.text = ""
            if (typeof fld_productId !== 'undefined') fld_productId.text = ""
            if (typeof fld_qty !== 'undefined') fld_qty.text = ""
            if (typeof fld_dueDate !== 'undefined') fld_dueDate.text = ""
            if (typeof fld_status !== 'undefined') fld_status.text = ""

        }
    }

    contentItem: ScrollView {
        width: 420; height: Math.min(implicitHeight, 480)
        ColumnLayout {
            width: parent.width
            spacing: 8
            TextField { placeholderText: "number"; id: fld_number; width: parent.width }
            Label { text: "number"; font.pointSize: 10 }
            TextField { placeholderText: "productId"; id: fld_productId; width: parent.width }
            Label { text: "productId"; font.pointSize: 10 }
            TextField { placeholderText: "qty"; id: fld_qty; width: parent.width }
            Label { text: "qty"; font.pointSize: 10 }
            TextField { placeholderText: "dueDate"; id: fld_dueDate; width: parent.width }
            Label { text: "dueDate"; font.pointSize: 10 }
            TextField { placeholderText: "status"; id: fld_status; width: parent.width }
            Label { text: "status"; font.pointSize: 10 }
        }
    }

    onAccepted: {
        var payload = {};
        (payload["number"] = fld_number.text)
        (payload["productId"] = fld_productId.text)
        (payload["qty"] = fld_qty.text)
        (payload["dueDate"] = fld_dueDate.text)
        (payload["status"] = fld_status.text)
        if (root.initial && root.initial.id !== undefined) payload.id = root.initial.id;
        root.created(payload);
    }
}

// Generated by surypus-codegen
