// Generated by surypus-codegen — DO NOT EDIT MANUALLY
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Dialog {
    id: root
    title: "Create ReportConfigEntity"
    modal: true
    standardButtons: Dialog.Ok | Dialog.Cancel
    signal created(var payload)
    property var initial: null

    onAboutToShow: {
        if (root.initial) {
            // prefill controls from initial
            if (typeof fld_title !== 'undefined') fld_title.text = root.initial["title"] !== undefined && root.initial["title"] !== null ? String(root.initial["title"]) : ""
            if (typeof fld_query !== 'undefined') fld_query.text = root.initial["query"] !== undefined && root.initial["query"] !== null ? String(root.initial["query"]) : ""
            if (typeof fld_refreshMinutes !== 'undefined') fld_refreshMinutes.text = root.initial["refreshMinutes"] !== undefined && root.initial["refreshMinutes"] !== null ? String(root.initial["refreshMinutes"]) : ""
            if (typeof fld_enabled !== 'undefined') fld_enabled.text = root.initial["enabled"] !== undefined && root.initial["enabled"] !== null ? String(root.initial["enabled"]) : ""

        } else {
            if (typeof fld_title !== 'undefined') fld_title.text = ""
            if (typeof fld_query !== 'undefined') fld_query.text = ""
            if (typeof fld_refreshMinutes !== 'undefined') fld_refreshMinutes.text = ""
            if (typeof fld_enabled !== 'undefined') fld_enabled.text = ""

        }
    }

    contentItem: ScrollView {
        width: 420; height: Math.min(implicitHeight, 480)
        ColumnLayout {
            width: parent.width
            spacing: 8
            TextField { placeholderText: "title"; id: fld_title; width: parent.width }
            Label { text: "title"; font.pointSize: 10 }
            TextField { placeholderText: "query"; id: fld_query; width: parent.width }
            Label { text: "query"; font.pointSize: 10 }
            TextField { placeholderText: "refreshMinutes"; id: fld_refreshMinutes; width: parent.width }
            Label { text: "refreshMinutes"; font.pointSize: 10 }
            TextField { placeholderText: "enabled"; id: fld_enabled; width: parent.width }
            Label { text: "enabled"; font.pointSize: 10 }
        }
    }

    onAccepted: {
        var payload = {};
        (payload["title"] = fld_title.text)
        (payload["query"] = fld_query.text)
        (payload["refreshMinutes"] = fld_refreshMinutes.text)
        (payload["enabled"] = fld_enabled.text)
        if (root.initial && root.initial.id !== undefined) payload.id = root.initial.id;
        root.created(payload);
    }
}

// Generated by surypus-codegen
