-- Generated SQL DDL from dsl/schema.yaml
-- DO NOT EDIT MANUALLY
-- Database: postgresql
-- Generator: surypus-codegen v0.1.0

-- Entity: PersonEntity
CREATE TABLE IF NOT EXISTS person (
    id BIGSERIAL NOT NULL,
    code TEXT,

    name TEXT NOT NULL,

    inn TEXT,

    kpp TEXT,

    personType TEXT NOT NULL,

    status TEXT,

    PRIMARY KEY (id)
);

-- Indexes for PersonEntity
CREATE INDEX IF NOT EXISTS idx_PersonEntity_name ON person (name);
CREATE INDEX IF NOT EXISTS idx_PersonEntity_personType ON person (personType);
-- Entity: CustomerEntity
CREATE TABLE IF NOT EXISTS customer (
    id BIGSERIAL NOT NULL,
    code TEXT NOT NULL,

    name TEXT NOT NULL,

    email TEXT,

    creditLimit TEXT,

    active TEXT NOT NULL,

    createdAt TEXT,

    PRIMARY KEY (id)
);

-- Indexes for CustomerEntity
CREATE INDEX IF NOT EXISTS idx_CustomerEntity_code ON customer (code);
CREATE INDEX IF NOT EXISTS idx_CustomerEntity_name ON customer (name);
CREATE INDEX IF NOT EXISTS idx_CustomerEntity_active ON customer (active);
-- Entity: ProductionOrderEntity
CREATE TABLE IF NOT EXISTS production_order (
    id BIGSERIAL NOT NULL,
    number TEXT NOT NULL,

    productId TEXT NOT NULL,

    qty TEXT NOT NULL,

    dueDate TEXT,

    status TEXT NOT NULL,

    PRIMARY KEY (id)
);

-- Indexes for ProductionOrderEntity
CREATE INDEX IF NOT EXISTS idx_ProductionOrderEntity_number ON production_order (number);
CREATE INDEX IF NOT EXISTS idx_ProductionOrderEntity_productId ON production_order (productId);
CREATE INDEX IF NOT EXISTS idx_ProductionOrderEntity_qty ON production_order (qty);
CREATE INDEX IF NOT EXISTS idx_ProductionOrderEntity_status ON production_order (status);
-- Entity: ReportConfigEntity
CREATE TABLE IF NOT EXISTS report_config (
    id BIGSERIAL NOT NULL,
    title TEXT NOT NULL,

    query TEXT NOT NULL,

    refreshMinutes TEXT,

    enabled TEXT NOT NULL,

    PRIMARY KEY (id)
);

-- Indexes for ReportConfigEntity
CREATE INDEX IF NOT EXISTS idx_ReportConfigEntity_title ON report_config (title);
CREATE INDEX IF NOT EXISTS idx_ReportConfigEntity_query ON report_config (query);
CREATE INDEX IF NOT EXISTS idx_ReportConfigEntity_enabled ON report_config (enabled);

-- Generated by surypus-codegen
