-- Generated SQL DDL from dsl/schema.yaml
-- DO NOT EDIT MANUALLY
-- Database: postgresql
-- Generator: surypus-codegen v0.1.0

-- Entity: PersonEntity
CREATE TABLE IF NOT EXISTS person (
    code TEXT,

    name TEXT NOT NULL,

    inn TEXT,

    kpp TEXT,

    personType TEXT NOT NULL,

    status TEXT,

    PRIMARY KEY (id)
);

-- Indexes for PersonEntity
CREATE INDEX IF NOT EXISTS idx_PersonEntity_name ON person (name;
CREATE INDEX IF NOT EXISTS idx_PersonEntity_personType ON person (personType;

-- Generated by surypus-codegen
