-- Api Tables
CREATE TABLE IF NOT EXISTS api_endpoint (id BIGSERIAL PRIMARY KEY, path VARCHAR(256) NOT NULL, method VARCHAR(16) NOT NULL, handler VARCHAR(256) NOT NULL, flags INTEGER DEFAULT 0, UNIQUE(path, method));
