{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module Schema where

import Data.Aeson (FromJSON, ToJSON)
import Data.Yaml (Value)
import qualified Data.Text as T
import GHC.Generics (Generic)

-- Generated from dsl/schema.yaml
-- DO NOT EDIT MANUALLY

data Schema = Schema
  { schemaVersion :: !T.Text
  , schemaDomain  :: !T.Text
  , schemaDatabase :: !T.Text
  , schemaGenerator :: !T.Text
  , schemaGeneratorVersion :: !T.Text
  , schemaEntities :: ![Entity]
  } deriving (Show, Generic)

instance FromJSON Schema
instance ToJSON Schema

data Entity = Entity
  { entityName    :: !T.Text
  , entitySqlTable :: !T.Text
  , entityFields  :: ![Field]
  } deriving (Show, Generic)

instance FromJSON Entity
instance ToJSON Entity

data Field = Field
  { fieldName     :: !T.Text
  , fieldType     :: !FieldType
  , fieldSqlType  :: !T.Text
  , fieldDefault  :: !(Maybe T.Text)
  , fieldNullable :: !Bool
  } deriving (Show, Generic)

instance FromJSON Field
instance ToJSON Field

data FieldType
  = FTInteger
  | FTSerial
  | FTBigInt
  | FTBoolean
  | FTText
  | FTVarchar
  | FTChar
  | FTReal
  | FTDouble
  | FTNumeric
  | FTDate
  | FTTimestamp
  | FTTime
  | FTJsonb
  | FTLtree
  | FTRange
  | FTCidr
  | FTInet
  | FTMacAddr
  | FTGeometry
  deriving (Show, Generic)

instance FromJSON FieldType
instance ToJSON FieldType

-- DSL entities:
-- Entity: PersonEntity
-- SQL table: person
-- Field: code
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: name
-- Type: FTText
-- SQL type: text
-- Nullable: False
-- Default: 
-- Field: inn
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: kpp
-- Type: FTText
-- SQL type: text
-- Nullable: True
-- Default: 
-- Field: personType
-- Type: FTText
-- SQL type: integer
-- Nullable: False
-- Default: 
-- Field: status
-- Type: FTText
-- SQL type: integer
-- Nullable: True
-- Default: 

-- Generated by surypus-codegen
