{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module DAL.Types where

import Data.Aeson (FromJSON, ToJSON)
import qualified Data.Text as T
import GHC.Generics (Generic)

-- Generated from dsl/schema.yaml
-- DO NOT EDIT MANUALLY

-- DSL entities:
-- Entity: PersonEntity
-- SQL table: person
data PersonEntity = PersonEntity
  { personEntityId :: !T.Text
  , code :: !T.Text
  , name :: !T.Text
  , inn :: !T.Text
  , kpp :: !T.Text
  , personType :: !T.Text
  , status :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (PersonEntity)
instance ToJSON (PersonEntity)

-- Entity: CustomerEntity
-- SQL table: customer
data CustomerEntity = CustomerEntity
  { customerEntityId :: !T.Text
  , code :: !T.Text
  , name :: !T.Text
  , email :: !T.Text
  , creditLimit :: !T.Text
  , active :: !T.Text
  , createdAt :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (CustomerEntity)
instance ToJSON (CustomerEntity)

-- Entity: ProductionOrderEntity
-- SQL table: production_order
data ProductionOrderEntity = ProductionOrderEntity
  { productionOrderEntityId :: !T.Text
  , number :: !T.Text
  , productId :: !T.Text
  , qty :: !T.Text
  , dueDate :: !T.Text
  , status :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (ProductionOrderEntity)
instance ToJSON (ProductionOrderEntity)

-- Entity: ReportConfigEntity
-- SQL table: report_config
data ReportConfigEntity = ReportConfigEntity
  { reportConfigEntityId :: !T.Text
  , title :: !T.Text
  , query :: !T.Text
  , refreshMinutes :: !T.Text
  , enabled :: !T.Text
  } deriving (Show, Generic)

instance FromJSON (ReportConfigEntity)
instance ToJSON (ReportConfigEntity)


-- Generated by surypus-codegen
