// Generated by surypus-codegen — DO NOT EDIT MANUALLY
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Page {
    id: root
    title: "PersonEntity"

    // Wire these signals in Main.qml to the RestClient calls, e.g.
    //   onLoadRequested: restClient.loadPersonEntitys()
    //   onCreateRequested: restClient.createPersonEntity(payload)
    signal loadRequested()
    signal createRequested(var payload)
    signal editRequested(var payload)

    Component.onCompleted: root.loadRequested()

    ListView {
        id: listView
        anchors.fill: parent
        anchors.margins: 12
        model: PersonEntitysModel
        delegate: ItemDelegate {
            text: modelData.code !== undefined ? modelData.code : JSON.stringify(modelData)
            width: listView.width
            onClicked: root.editRequested(modelData)
        }
    }

    footer: ToolBar {
        ToolButton { text: "Refresh"; onClicked: root.loadRequested() }
        ToolButton { text: "New"; onClicked: dlg.open() }
    }

    PersonEntityDialog {
        id: dlg
        onCreated: function(payload) { root.createRequested(payload); dlg.close() }
    }
}

// Generated by surypus-codegen
