cabal-version: 3.0
name:                surypus-api
version:             0.1.0.0
synopsis:            REST API Backend for Surypus ERP
license:             AGPL-3.0-only
author:              dominicusin
maintainer:          dev@surypus.com
category:            Web

library
  exposed-modules:
    Surypus.API.Server
    Surypus.API.Dashboard
    Surypus.API.CRM
    Surypus.API.Notifications
    Surypus.API.Reports
    Surypus.API.Orders
    Surypus.API.Workflow
    Surypus.API.Bills
    Surypus.API.Payment
    Surypus.API.Persons
    Surypus.API.Goods
    Surypus.API.Auth
    Surypus.API.Logger
    Surypus.JWT.Token
    Surypus.API.AI
    Infrastructure.Email
  other-modules:
    DAL.Queries
    DAL.Mutations
    DAL.Repository
    DAL.Database
  build-depends:
      base              >= 4.16 && < 4.18
    , Surypus           == 0.1.0.0
    , surypus-common    == 0.1.0.0
    , text              >= 2.0
    , servant           >= 0.20
    , servant-server    >= 0.20
    , wai               >= 3.2
    , warp              >= 3.3
    , http-types
    , aeson
    , postgresql-binary
    , time
    , containers
    , mtl
    , bytestring
    , transformers      >= 0.5
    , websockets
    , wai-websockets
    , uuid              >= 1.3
    , fast-logger       >= 3.2
    , hasql
    , hasql-pool
    , jose              >= 0.10 && < 0.11
    , cryptonite        >= 0.30
    , lens
    , network-uri
    , smtp-mail
    , mime-mail
    , http-client
    , http-conduit
  hs-source-dirs:      src, src/Surypus
  default-language:    Haskell2010
  ghc-options:         -Wall -Wcompat

test-suite surypus-api-test
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
    Surypus.JWT.TokenSpec
    Surypus.AITest
  build-depends:
    base,
    surypus-api,
    hspec,
    hspec-core,
    text,
    jose,
    lens,
    bytestring,
    aeson,
    time
  hs-source-dirs: test
  default-language: Haskell2010
  ghc-options: -Wall -Wcompat

executable surypus-api
  main-is:             Main.hs
  build-depends:
      base
    , surypus-api
    , warp
    , time
    , hasql
    , hasql-pool
  hs-source-dirs:      app
  default-language:    Haskell2010
  ghc-options:         -Wall -Wcompat -threaded -rtsopts -with-rtsopts=-N -O2
  default-extensions:  OverloadedStrings DuplicateRecordFields DeriveGeneric
