apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "surypus.fullname" . }}
  labels:
    {{- include "surypus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "surypus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "surypus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.database.name | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
