name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.6.6', '9.8.4']
        postgres: ['14', '15']
    steps:
      - uses: actions/checkout@v4
      - name: Install Haskell Stack
        run: |
          curl -sSL https://get.haskellstack.org/ | sh
      - name: Install HLint
        run: |
          stack install hlint
      - name: Setup GHC
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Build
        run: |
          stack --version
          stack build --test --no-run-tests
      - name: Run tests
        run: |
          stack test --test-arguments --color
      - name: HLint
        run: |
          ~/.local/bin/hlint src/ test/ --color
      - name: HLint Pedantic
        run: |
          ~/.local/bin/hlint src/ test/ --pedantic --color
      - name: Dry-run migrations
        run: |
          bash scripts/ci-dry-run-mig.sh
      - name: Migration Verification
        run: |
          bash scripts/check_schema_uniqueness.sh || true
